export const league = {
  name: 'NBA',
  logo: 'https://via.placeholder.com/300.png/09f/fff',
  teams: [
    {
      id: 'sr:competitor:3433',
      name: 'Toronto Raptors',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'TOR',
      state: 'NN',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3426',
      name: 'Minnesota Timberwolves',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'MIN',
      state: 'MN',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3431',
      name: 'Washington Wizards',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'WAS',
      state: 'DC',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3417',
      name: 'Denver Nuggets',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'DEN',
      state: 'CO',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3437',
      name: 'Orlando Magic',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'ORL',
      state: 'FL',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3423',
      name: 'Atlanta Hawks',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'ATL',
      state: 'GA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3432',
      name: 'Cleveland Cavaliers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'CLE',
      state: 'OH',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3424',
      name: 'Detroit Pistons',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'DET',
      state: 'MI',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3411',
      name: 'Dallas Mavericks',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'DAL',
      state: 'TX',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3410',
      name: 'Milwaukee Bucks',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'MIL',
      state: 'WI',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3419',
      name: 'Indiana Pacers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'IND',
      state: 'IN',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3429',
      name: 'San Antonio Spurs',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'SAS',
      state: 'TX',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3412',
      name: 'Houston Rockets',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'HOU',
      state: 'TX',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3434',
      name: 'Utah Jazz',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'UTA',
      state: 'UT',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3418',
      name: 'Oklahoma City Thunder',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'OKC',
      state: 'OK',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3409',
      name: 'Chicago Bulls',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'CHI',
      state: 'IL',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3414',
      name: 'Portland Trail Blazers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'POR',
      state: 'OR',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3435',
      name: 'Miami Heat',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'MIA',
      state: 'FL',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3421',
      name: 'New York Knicks',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'NYK',
      state: 'NY',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3427',
      name: 'Los Angeles Lakers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'LAL',
      state: 'CA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3413',
      name: 'Sacramento Kings',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'SAC',
      state: 'CA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3436',
      name: 'Brooklyn Nets',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'BKN',
      state: 'NY',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3420',
      name: 'Philadelphia 76ers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'PHI',
      state: 'PA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3422',
      name: 'Boston Celtics',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'BOS',
      state: 'MA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3416',
      name: 'Phoenix Suns',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'PHX',
      state: 'AZ',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:5539',
      name: 'New Orleans Pelicans',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'NOP',
      state: 'LA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3428',
      name: 'Golden State Warriors',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'GSW',
      state: 'CA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3425',
      name: 'LA Clippers',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'LAC',
      state: 'CA',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3415',
      name: 'Memphis Grizzlies',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'MEM',
      state: 'TN',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
    {
      id: 'sr:competitor:3430',
      name: 'Charlotte Hornets',
      country: 'USA',
      countryCode: 'USA',
      abbreviation: 'CHA',
      state: 'NC',
      logo: 'https://via.placeholder.com/300.png/09f/fff',
    },
  ],
};
